USE movies

--1--
SELECT STARNAME FROM STARSIN
WHERE MOVIETITLE='The Usual Suspects'
INTERSECT 
SELECT NAME FROM MOVIESTAR
WHERE GENDER='M'
 
--2--
SELECT STARNAME AS starname FROM STARSIN
WHERE MOVIETITLE IN (
SELECT MOVIETITLE FROM STARSIN
WHERE MOVIEYEAR=1995
INTERSECT
SELECT TITLE FROM MOVIE 
WHERE STUDIONAME='MGM'
)

--3--
SELECT NAME FROM MOVIEEXEC WHERE CERT# IN (
SELECT PRODUCERC# FROM MOVIE
WHERE STUDIONAME='MGM'
INTERSECT
SELECT CERT# FROM MOVIEEXEC
)

--4--
SELECT TITLE AS title FROM MOVIE
WHERE LENGTH > (
SELECT LENGTH
FROM MOVIE
WHERE TITLE='Star Wars'
)

--5--
SELECT NAME FROM MOVIEEXEC 
WHERE NETWORTH > (
SELECT NETWORTH 
FROM MOVIEEXEC 
WHERE NAME='Stephen Spielberg'
)

--6--
SELECT TITLE FROM MOVIE
WHERE PRODUCERC# IN (
SELECT CERT# FROM MOVIEEXEC 
WHERE NETWORTH > (
SELECT NETWORTH
FROM MOVIEEXEC 
WHERE NAME='Stephen Spielberg' 
))


USE pc

--1--
SELECT maker, l.speed
FROM product AS p
JOIN laptop l 
ON l.model=p.model
WHERE l.hd >= 9

--2--
SELECT model, price FROM printer
WHERE model IN (SELECT model FROM product WHERE maker='B')
UNION
SELECT  model, price FROM pc
WHERE model IN (SELECT model FROM product WHERE maker='B')
UNION 
SELECT  model, price FROM laptop
WHERE model IN (SELECT model FROM product WHERE maker='B')

--3--
SELECT maker FROM product
WHERE maker NOT IN (
SELECT maker FROM product 
WHERE type LIKE 'PC'
)
AND type LIKE 'Laptop'

--4--
SELECT hd
FROM pc
GROUP BY hd
HAVING COUNT(hd) >= 2

--5-- not done
SELECT * FROM pc

SELECT * FROM pc
WHERE model IN (
SELECT model FROM pc)

--6-- not done
SELECT maker FROM product
WHERE model IN (
   SELECT model FROM pc
   WHERE speed >= 400
   GROUP BY model
   HAVING COUNT(model) = 1
)


USE ships

--1--
SELECT [NAME] AS name FROM SHIPS
WHERE CLASS IN (
   SELECT CLASS FROM CLASSES
   WHERE DISPLACEMENT > 50000
)

--2--
SELECT NAME AS name,
DISPLACEMENT AS displacement,
NUMGUNS AS numguns
FROM CLASSES AS c
RIGHT JOIN ( 
SELECT NAME, CLASS FROM SHIPS AS s
JOIN OUTCOMES AS o
ON o.SHIP=s.NAME
WHERE o.BATTLE='Guadalcanal'
) AS t ON t.CLASS=c.CLASS

--3--
SELECT COUNTRY AS country FROM CLASSES
WHERE TYPE='bb'
INTERSECT
SELECT COUNTRY FROM CLASSES
WHERE TYPE='bc'

--4--
SELECT SHIP AS ship FROM OUTCOMES
WHERE RESULT='damaged'
INTERSECT
SELECT SHIP FROM OUTCOMES
WHERE RESULT='ok'

