USE movies

--1--
SELECT
TITLE AS title, YEAR as year, LENGTH AS length 
FROM MOVIE
WHERE (LENGTH > 120 OR LENGTH IS NULL) 
AND YEAR < 2000

--2--
SELECT
NAME AS name, GENDER AS gender
FROM MOVIESTAR
WHERE SUBSTRING(NAME, 1, 1)='J'
AND BIRTHDATE > 1948
ORDER BY NAME DESC

--3--
SELECT
  STUDIONAME AS studioname,
  COUNT(DISTINCT(s.STARNAME)) AS num_actors
FROM MOVIE AS m
JOIN STARSIN AS s
ON s.MOVIETITLE=m.TITLE
GROUP BY STUDIONAME

--4--
SELECT 
  m.NAME AS starname,
  COUNT(s.MOVIETITLE) AS num_movies
FROM MOVIESTAR AS m
JOIN STARSIN AS s
ON s.STARNAME=m.NAME
GROUP BY m.NAME

--5--
SELECT
m.STUDIONAME, m.TITLE, r.year
FROM MOVIE AS m
JOIN 
(
  SELECT
  STUDIONAME, MAX(YEAR) AS year
  FROM MOVIE
  GROUP BY STUDIONAME
) AS r
ON r.STUDIONAME=m.STUDIONAME
WHERE m.YEAR=r.year

--6--
SELECT NAME
FROM MOVIESTAR
WHERE BIRTHDATE >= ALL (
  SELECT BIRTHDATE
  FROM MOVIESTAR
  WHERE GENDER='M'
) AND GENDER='M'

--7--
SELECT
m.STUDIONAME, s.STARNAME, COUNT(m.TITLE) AS num_movies
FROM STARSIN AS s
JOIN MOVIE AS m
ON m.TITLE=s.MOVIETITLE
GROUP BY m.STUDIONAME, s.STARNAME
HAVING COUNT(m.TITLE) >= ALL (
  SELECT COUNT(m.TITLE) AS num_movies
  FROM STARSIN AS s
  JOIN MOVIE AS m
  ON m.TITLE=s.MOVIETITLE
  GROUP BY m.STUDIONAME, s.STARNAME
)
ORDER BY COUNT(m.TITLE) DESC

--8--
SELECT TOP(1)
m.TITLE AS movietitle,
m.YEAR AS movieyear,
COUNT(s.STARNAME) AS num_actors
FROM MOVIE AS m
JOIN STARSIN AS s
ON s.MOVIETITLE=m.TITLE
GROUP BY m.TITLE, m.YEAR
ORDER BY num_actors DESC


USE ships

--1--
SELECT
DISTINCT s.NAME AS ship
FROM SHIPS AS s
JOIN OUTCOMES AS o
ON o.SHIP=s.NAME
WHERE (SUBSTRING(s.NAME, 1, 1) = 'C' 
OR SUBSTRING(s.NAME, 1, 1) = 'K')

--2--
SELECT DISTINCT
s.NAME AS name, c.COUNTRY
FROM SHIPS AS s
LEFT JOIN OUTCOMES AS o
ON o.SHIP=s.NAME
JOIN CLASSES AS c
ON c.CLASS=s.CLASS
WHERE s.NAME NOT IN
(
  SELECT SHIP
  FROM OUTCOMES
  WHERE RESULT='sunk'
)

--3--
SELECT
  c.COUNTRY AS country,
  COUNT(s.NAME) AS num_sunk_ships
FROM CLASSES AS c
LEFT JOIN SHIPS AS s
ON s.CLASS=c.CLASS
LEFT JOIN OUTCOMES AS o
ON o.SHIP=s.NAME
WHERE o.RESULT='sunk'
GROUP BY c.COUNTRY

SELECT
  c.COUNTRY AS country,
  COUNT(s.NAME) AS num_sunk_ships
FROM SHIPS AS s
RIGHT JOIN CLASSES AS c
ON s.CLASS=c.CLASS
LEFT JOIN OUTCOMES AS o
ON o.SHIP=s.NAME
WHERE o.RESULT='sunk'
GROUP BY c.COUNTRY

SELECT c.COUNTRY, COUNT(s.NAME)
FROM CLASSES AS c
LEFT JOIN SHIPS AS s
ON s.CLASS=c.CLASS
GROUP BY c.COUNTRY

SELECT
  COUNTRY,
  COUNT(s.NAME) AS ships_count
FROM CLASSES AS c
FULL JOIN SHIPS AS s
ON s.CLASS=c.CLASS
FULL JOIN (
  SELECT SHIP FROM OUTCOMES 
  WHERE RESULT = 'sunk'
) AS f
ON f.SHIP=s.NAME
GROUP BY COUNTRY